### ISSUE TITLE
dio_firebase_performance does not compile with dio: ^4.0.0-prev2

### ISSUE THREAD

**Issue by andreacimino** [eyeem/dio_firebase_performance#13]
Seems dio has changed the API of the 4.0 versions, and the package does not compile anymore.

Here are the errors:
`../../.pub-cache/hosted/pub.dartlang.org/dio-4.0.0-prev2/lib/src/interceptor.dart:225:8: Context: This is the overridden method ('onError').
  void onError(
       ^
../../../.pub-cache/git/dio_firebase_performance-9cbaeebb70c6fc9cf6f4a202b70b5f82781f224d/lib/src/dio_firebase_performance.dart:39:27: Error: Too few positional arguments: 2 required, 1 given.
    return super.onRequest(options);
                          ^

../../../.pub-cache/git/dio_firebase_performance-9cbaeebb70c6fc9cf6f4a202b70b5f82781f224d/lib/src/dio_firebase_performance.dart:45:35: Error: The getter 'request' isn't defined for the class 'Response<dynamic>'.
 - 'Response' is from 'package:dio/src/response.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/dio-4.0.0-prev2/lib/src/response.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'request'.
      final requestKey = response.request.extra.hashCode;
                                  ^^^^^^^
../../../.pub-cache/git/dio_firebase_performance-9cbaeebb70c6fc9cf6f4a202b70b5f82781f224d/lib/src/dio_firebase_performance.dart:51:28: Error: Too few positional arguments: 2 required, 1 given.
    return super.onResponse(response);
                           ^
../../../.pub-cache/git/dio_firebase_performance-9cbaeebb70c6fc9cf6f4a202b70b5f82781f224d/lib/src/dio_firebase_performance.dart:57:30: Error: The getter 'request' isn't defined for the class 'DioError'.
 - 'DioError' is from 'package:dio/src/dio_error.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/dio-4.0.0-prev2/lib/src/dio_error.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'request'.
      final requestKey = err.request?.extra.hashCode;
                             ^^^^^^^
`

**Comment by smurat** [comment]
@andreacimino I have the same problem. Can you fix it?

**Comment by andreacimino** [comment]
> @andreacimino I have the same problem. Can you fix it?

I have sent a pull request with the patch.

**Comment by fannt** [comment]
thanks for the issue, looking into it

**Comment by andreacimino** [comment]
You can look at https://github.com/eyeem/dio_firebase_performance/pull/14, that should solve the issue
